spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 500
        min-idle: 100
        max-active: 2000
        max-wait: 100000
    timeout: 10000
    password:
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tokendemo?useUnicode=true&characterEncoding=utf-8&useSSL=false

mybatis-plus:
  type-aliases-package: com.fanlun.redislock.entity

logging:
  level:
    com.fanlun.redislock: debug